global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
  - job_name: node_main
    static_configs:
      - targets: ["host.docker.internal:9100"]
        labels:
          instance: main

  - job_name: cadvisor_main
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          instance: main

  - job_name: backend
    static_configs:
      - targets: ["host.docker.internal:8001"]
        labels:
          instance: main

  - job_name: agents
    metrics_path: /metrics-prom
    authorization:
      credentials_file: /etc/prometheus/agent_token
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/agents.json
        refresh_interval: 30s