"""unique port per server

Revision ID: 28600d1d50c4
Revises: a1b2c3d4e5f6
Create Date: 2026-03-11 19:27:24.917377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28600d1d50c4'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('access_keys_ss_port_key'), 'access_keys', type_='unique')
    op.create_unique_constraint(None, 'access_keys', ['server_id', 'ss_port'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'access_keys', type_='unique')
    op.create_unique_constraint(op.f('access_keys_ss_port_key'), 'access_keys', ['ss_port'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
