"""initial

Revision ID: bf0a31f81f0d
Revises: 
Create Date: 2026-02-08 23:07:17.063880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0a31f81f0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('port_range_start', sa.Integer(), nullable=False),
    sa.Column('port_range_end', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('bandwidth_used', sa.BigInteger(), nullable=False),
    sa.Column('connected_users', sa.Integer(), nullable=False),
    sa.Column('ssh_user', sa.String(length=50), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('ssh_key_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('free', 'basic', 'pro', name='plantype'), nullable=False),
    sa.Column('traffic_limit', sa.BigInteger(), nullable=False),
    sa.Column('traffic_used', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('access_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('ss_port', sa.Integer(), nullable=False),
    sa.Column('ss_password', sa.String(length=255), nullable=False),
    sa.Column('ss_method', sa.String(length=50), nullable=False),
    sa.Column('traffic_up', sa.BigInteger(), nullable=False),
    sa.Column('traffic_down', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ss_port')
    )
    op.create_table('traffic_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('access_key_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('bytes_up', sa.BigInteger(), nullable=False),
    sa.Column('bytes_down', sa.BigInteger(), nullable=False),
    sa.Column('upload_speed', sa.Float(), nullable=False),
    sa.Column('download_speed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['access_key_id'], ['access_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_logs')
    op.drop_table('access_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('servers')
    # ### end Alembic commands ###
